markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - kramdown
  - rouge
  - jekyll-watch
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
paginate: 10
host: 0.0.0.0
port: 4000

collections:
  speakers:
      output: true
      permalink: /:collection/:name
  papers:
      output: true
      permalink: /:collection/:name
  meetups:
      output: true
      permalink: /:collection/:name

