markdown: kramdown
theme: minima
gems:
  - kramdown
  - rouge
  - jekyll-watch
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
paginate: 10
paginate_path: "/posts/page:num/"
host: 0.0.0.0
port: 4000

future: true

permalink: /:categroy/:title/

collections:
  speakers:
      output: true
      permalink: /:collection/:name
  papers:
      output: true
      permalink: /:collection/:name
  meetups:
      output: true
      permalink: /:collection/:name
  jobs:
      output: true
      permalink: /:collection/:name
